env:
  browser: true
  es2021: true
  node: false
extends:
  - prettier
  - eslint:recommended
  - plugin:import/recommended
  - eslint:recommended
plugins:
  - prettier
  - import
rules:
  prettier/prettier:
    - error
  indent: off
  arrow-parens: off
  arrow-spacing:
    - warn
    - before: true
      after: true
  brace-style:
    - error
    - 1tbs
    - allowSingleLine: true
  comma-spacing: error
  comma-style: error
  curly:
    - error
    - multi-line
    - consistent
  dot-location:
    - error
    - property
  handle-callback-err: 'off'
  keyword-spacing: error
  max-nested-callbacks:
    - error
    - max: 4
  max-statements-per-line:
    - error
    - max: 1
  no-console:
    - error
    - allow:
        - warn
        - error
        - info
        - debug
  no-empty-function: error
  no-floating-decimal: error
  no-inline-comments: error
  no-lonely-if: error
  no-multi-spaces: error
  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 1
      maxBOF: 0
  no-shadow: 'off'
  no-trailing-spaces:
    - error
  no-var: error
  prefer-const: error
  space-before-blocks: error
  space-before-function-paren:
    - error
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: error
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  yoda: error
  import/no-commonjs: error
  import/no-amd: error
  import/no-unresolved:
    - warn
    - ignore:
        - '^@/'
  import/no-deprecated: error
  import/named: error
  import/namespace: error
  import/default: error
  import/export: error
  import/order:
    - error
    - newlines-between: always
      warnOnUnassignedImports: true
      groups:
        - builtin
        - external
        - internal
        - parent
        - sibling
        - index
        - object
        - type
      alphabetize:
        order: asc
